# Generated by Django 4.1.4 on 2023-01-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
